# Generated by Django 4.0.3 on 2022-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
