# Generated by Django 4.0.3 on 2022-04-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0002_books_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_log',
            name='date_exp',
        ),
        migrations.RemoveField(
            model_name='books_log',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='books_log',
            name='date_returned',
        ),
    ]
