# Generated by Django 4.0.3 on 2022-04-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0003_remove_books_log_date_exp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_log',
            old_name='book',
            new_name='book_title',
        ),
        migrations.RenameField(
            model_name='books_log',
            old_name='user',
            new_name='username',
        ),
    ]
