# Generated by Django 4.0.3 on 2022-04-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0004_rename_book_books_log_book_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_log',
            old_name='book_title',
            new_name='book_id',
        ),
    ]
