# Generated by Django 4.0.3 on 2022-04-18 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebAPI', '0005_rename_book_title_books_log_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_log',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='books_log',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='books',
            name='users',
            field=models.ManyToManyField(through='WebAPI.Books_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
