# Generated by Django 4.0.3 on 2022-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0006_rename_book_id_books_log_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_log',
            name='date_exp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='books_log',
            name='date_issued',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='books_log',
            name='date_returned',
            field=models.DateField(auto_now=True),
        ),
    ]
